version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: conference_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:8.2-fpm
    container_name: conference_php
    volumes:
      - ./www:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge